// ignore_for_file: file_names

 /// Flutter icons CustomeIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomeIcons
///      fonts:
///       - asset: Files/Icons/CustomeIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomeIcons {
  CustomeIcons._();

  static const _kFontFam = 'CustomeIcons';
  static const String? _kFontPkg = null;

  static const IconData windows = IconData(0xf17a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android = IconData(0xf17b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linux = IconData(0xf17c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
